version: 2
jobs:
  prepare_ci:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: android/Smartbread
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  DebugBuild:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Build
          command: android/Startbread/gradlew assembleDebug
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: android/Startbread/app/build/reports
          destination: reports
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: android/Startbread/app/build/test-results

  ReleaseBuild:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Build
          command: android/Startbread/gradlew assembleRelease
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: android/Startbread/app/build/reports
          destination: reports
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: android/Startbread/app/build/test-results
  test:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Build
          command: android/Startbread/gradlew test
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: android/Startbread/app/build/reports
          destination: reports
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: android/Startbread/app/build/test-results
  lint:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Build
          command: android/Startbread/gradlew lint
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: android/Startbread/app/build/reports
          destination: reports
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: android/Startbread/app/build/test-results
  Danger:
    working_directory: ~/code
      docker:
          - image: circleci/android:api-29-node
      environment:
        JVM_OPTS: -Xmx3200m
      steps:
        - attach_workspace:
            at: .
        - run:
            name: install bundle
            command: bundle install
        - run:
            name: Run Danger
            command: bundle exec danger --fail-on-errors=true
workflows:
  version: 2
  main:
    jobs:
      - prepare_ci
      - DebugBuild:
          requires:
            - prepare_ci
      - ReleaseBuild:
          requires:
            - DebugBuild
      - test:
          requires:
            - DebugBuild
      - Danger:
          requires:
            - DebugBuild
      - lint:
          requires:
            - DebugBuild